# NLU Tool
NLU_MODEL_ID = "tone-classifications-en-v1"
NLU_API_KEY = "YOUR_API_KEY_HERE"
NLU_URL = "YOUR_URL_HERE"

# STT Tool
STT_API_KEY = "YOUR_API_KEY_HERE"
STT_URL = "YOUR_URL_HERE"
STT_MODEL_ID = "en-GB_Multimedia"